momentum:
  confidence_buy: 72.0
  confidence_sell: 72.0
  confidence_hold: 18.0

mean_reversion:
  rsi_buy: 30
  rsi_sell: 70
  confidence_buy: 60.0
  confidence_sell: 60.0
  confidence_hold: 20.0

breakout:
  lookback: 20
  volume_multiple: 1.5
  confidence_buy: 65.0
  confidence_sell: 65.0
  confidence_hold: 15.0

volatility:
  low_threshold: 0.2
  high_threshold: 0.5
  confidence_low: 32.0
  confidence_high: 55.0
  confidence_mid: 25.0

aggregate:
  buy_threshold: 0.15
  sell_threshold: -0.15
  risk_reward_floor: 1.1
  base_conf_multiplier: 155.0
  mc_trials: 1800
  vector_bias:
    momentum_alignment: 0.12
    momentum_bias_weight: 0.24
    breakout_slope_weight: 0.1
    volatility_mid_bias: 0.05
    volatility_high_bias: 0.12
    volatility_low_bias: -0.06
  multi_timeframe:
    slope_scale: 90.0
    intraday_scale: 8.0
    ema21_slope_weight: 0.22
    intraday_momentum_weight: 0.18
    alignment_shift: 0.08

